### ISSUE TITLE
Well hover over not working as soon as wells created

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#163]
### Observed
- Create two well points in immediate succession
- Hover-over well table records _**will not**_ highlight associated well point on map
- Refresh page
- Hover-over well table records **_will_** highlight point on map
- (Note: Hover-over well points on map does highlight associated table records, as expected)

### Expected
- Create two well points in immediate succession
- Hover-over well table records will highlight point on map without having to refresh page

**Comment by steveoh** [comment]
I suspect the original graphic is on top of the one that has the hover styling.

**Comment by nathankota** [comment]
Tested on site [62, inventory 111](https://uic-inventory.dev.utah.gov/site/62/inventory/111/add-wells), but still no worky until page is refreshed. 

![image](https://user-images.githubusercontent.com/15659642/154376727-de8adc71-d73b-41ba-80e6-aebd3c82476f.png)

**Comment by steveoh** [comment]
This is fixed in 4.23 and I'll update soon.

**Comment by nathankota** [comment]
This still requires a page refresh before the table record hover-over will highlight the associated point on the map.

**Comment by steveoh** [comment]
Please try clearing your cache. I've tested this locally and in dev and it worked as expected.

**Comment by nathankota** [comment]
I cleared cache and tried a couple browsers and hovering over the table record still does not highlight the point until the page has been refreshed

![image](https://user-images.githubusercontent.com/15659642/236938959-1c7eb5fe-ff44-4ff3-80ff-2920f3b551e8.png)

**Comment by nathankota** [comment]
@rsparker-utah can you please test this and see if it works for you?

**Comment by steveoh** [comment]
Scott and I looked into this a bit today and our code is doing what it's supposed to do. This appears to continue to be an esri issue. Scott noticed if you have more than one well then the hovering works without requiring a refresh.

**Comment by nathankota** [comment]
> Scott noticed if you have more than one well then the hovering works without requiring a refresh.

Interesting. All of my tests included creating multiple wells in tandem, and refresh was always required for the points to be highlighted when hovering over the "table" record. Thanks for taking a deeper look at this. Time to put it at the bottom of the pile, or I might close it 🤔

**Comment by steveoh** [comment]
I think I fixed this for good this time.

**Comment by rsparker-utah** [comment]
This is working for me as well.
